/**
 * @file This script is auto-generated by create-nitro-module and should not be edited.
 *
 * @description This script applies a workaround for Android by modifying the '<ModuleName>OnLoad.cpp' file.
 * It reads the file content and removes the 'margelo/nitro/' string from it. This enables support for custom package names.
 *
 * @module create-nitro-module
 */
const path = require('node:path')
const { writeFile, readFile } = require('node:fs/promises')

const androidWorkaround = async () => {
  const androidOnLoadFile = path.join(
    process.cwd(),
    'nitrogen/generated/android',
    'ClamshellOnLoad.cpp'
  )

  const str = await readFile(androidOnLoadFile, { encoding: 'utf8' })
  await writeFile(androidOnLoadFile, str.replace(/margelo\/nitro\//g, ''))
}

const applyAndroidWorkletsBridge = async () => {
  const androidAutolinkingFile = path.join(
    process.cwd(),
    'nitrogen/generated/android',
    'Clamshell+autolinking.cmake'
  )

  let str = await readFile(androidAutolinkingFile, { encoding: 'utf8' })
  if (!str.includes('../cpp/AngleRuntimeBridge.cpp')) {
    str = str.replace(
      '  ../nitrogen/generated/android/c++/JVariant_NullType_FoldGeometry.cpp\n',
      '  ../nitrogen/generated/android/c++/JVariant_NullType_FoldGeometry.cpp\n  ../cpp/AngleRuntimeBridge.cpp\n'
    )
  }
  if (!str.includes('find_package(react-native-worklets REQUIRED CONFIG)')) {
    str = str.replace(
      'find_package(react-native-nitro-modules REQUIRED) # <-- Used to create all HybridObjects and use the Nitro core library\n',
      'find_package(react-native-nitro-modules REQUIRED) # <-- Used to create all HybridObjects and use the Nitro core library\nfind_package(react-native-worklets REQUIRED CONFIG)\n'
    )
  }
  if (!str.includes('react-native-worklets::worklets')) {
    str = str.replace(
      '        react-native-nitro-modules::NitroModules  # <-- NitroModules Core :)\n',
      '        react-native-nitro-modules::NitroModules  # <-- NitroModules Core :)\n        react-native-worklets::worklets\n'
    )
  }

  await writeFile(androidAutolinkingFile, str)
}

const applyIosWorkletsBridge = async () => {
  const iosAutolinkingFile = path.join(
    process.cwd(),
    'nitrogen/generated/ios',
    'ClamshellAutolinking.mm'
  )

  let str = await readFile(iosAutolinkingFile, { encoding: 'utf8' })
  if (!str.includes('#include "AngleRuntimeBridge.hpp"')) {
    str = str.replace(
      '#include "HybridClamshellSpecSwift.hpp"\n',
      '#include "HybridClamshellSpecSwift.hpp"\n#include "AngleRuntimeBridge.hpp"\n'
    )
  }
  if (!str.includes('"AngleRuntimeHost"')) {
    str = str.replace(
      '  using namespace margelo::nitro::clamshell;\n\n',
      `  using namespace margelo::nitro::clamshell;

  HybridObjectRegistry::registerHybridObjectConstructor(
    "AngleRuntimeHost",
    []() -> std::shared_ptr<HybridObject> {
      return ::clamshell::createAngleRuntimeHostObject();
    }
  );

`
    )
  }

  await writeFile(iosAutolinkingFile, str)
}

const run = async () => {
  await androidWorkaround()
  await applyAndroidWorkletsBridge()
  await applyIosWorkletsBridge()
}

run()
