name: Run React Native Harness iOS

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/harness-ios.yml'
      - 'example/**'
      - 'android/**'
      - 'ios/**'
      - 'cpp/**'
      - 'src/**'
      - 'nitrogen/**'
      - '*.podspec'
      - 'package.json'
      - 'yarn.lock'
      - 'react-native.config.js'
      - 'nitro.json'
  pull_request:
    paths:
      - '.github/workflows/harness-ios.yml'
      - 'example/**'
      - 'android/**'
      - 'ios/**'
      - 'cpp/**'
      - 'src/**'
      - 'nitrogen/**'
      - '*.podspec'
      - 'package.json'
      - 'yarn.lock'
      - 'react-native.config.js'
      - 'nitro.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test iOS Harness
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'yarn'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.5.app/Contents/Developer

      - name: Install Pods
        run: yarn pod

      - name: Build iOS app
        env:
          IOS_BUILD_CONFIGURATION: Debug
          IOS_DERIVED_DATA_PATH: example/ios/build
        run: yarn build:ios

      - name: Run React Native Harness
        uses: callstackincubator/react-native-harness@v1.2.0
        with:
          app: ios/build/Build/Products/Debug-iphonesimulator/ClamshellExample.app
          runner: ios
          projectRoot: example
          packageManager: yarn
